# Generated by Django 4.1.2 on 2022-11-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='price_per_night',
            new_name='price',
        ),
    ]
