# Generated by Django 4.1.2 on 2022-11-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_rename_price_per_night_house_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='price',
            new_name='price_per_night',
        ),
    ]
