# Generated by Django 4.1.2 on 2022-11-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_rename_price_house_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='pets_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
