# Generated by Django 4.1.2 on 2022-11-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_pets_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='pets_allowed',
        ),
    ]
