# Generated by Django 4.1.2 on 2022-11-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_house_pets_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='pets_allowed',
            field=models.BooleanField(default=True, help_text='Does this house allow pets?', verbose_name='Pets Allowed?'),
        ),
    ]
